version: '3.8'
services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ../web-ui
      dockerfile: ../docker/frontend/Dockerfile
      args:
        - VITE_WS_URL=ws://localhost:8080/ws
        - VITE_WS_PORT=8080
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
